GET http://localhost:3000/notes

### 
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Hazelnut Recipe",
    "description": "Special recipe for roasted hazelnuts with honey glaze",
    "tags": ["cooking", "recipes", "nuts"],
    "image": "hazelnuts.jpg"
}

### 
PATCH  http://localhost:3000/notes/2
Content-Type: application/json

{
    "title": "Updated Hazelnut Recipe",
    "description": "Updated recipe with additional spices",
    "tags": ["cooking", "recipes", "nuts", "updated"]
}

###
DELETE http://localhost:3000/notes/1



